# Generated by Django 2.1 on 2018-10-03 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='优惠码')),
                ('valid_from', models.DateTimeField(verbose_name='有效起始时间')),
                ('valid_to', models.DateTimeField(verbose_name='有效结束时间')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='折扣率')),
                ('active', models.BooleanField()),
            ],
        ),
    ]
