# Generated by Django 2.1.2 on 2018-10-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181005_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='moudle',
            new_name='module',
        ),
    ]
